{% set name = "napari-pyclesperanto-assistant" %}
{% set version = "0.18.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_pyclesperanto_assistant-{{ version }}.tar.gz
  sha256: e2673aa5afafa9b6ffa034b80e625031bf06b622a79258fcc150a2ec40778602

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - jupyter
    - jupytext
    - loguru
    - magicgui
    - napari >=0.4.15
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.2.0
    - napari-time-slicer >=0.4.0
    - napari-tools-menu >=0.1.8
    - napari-workflows >=0.1.1
    - numpy !=1.19.4
    - pandas
    - pyclesperanto-prototype >=0.17.1
    - pyopencl
    - pyperclip
    - python >=3.6
    - scikit-image
    - toolz
    - typing_extensions
    - napari-assistant >=0.1.10

test:
  imports:   # [not linux]
    - napari_pyclesperanto_assistant  # [not linux]
  commands:
    - pip list
    # - pip check
    - xvfb-run -a python -c "import napari_pyclesperanto_assistant"  # [linux]
  requires:
    - oclgrind  # [win]
    - pip
    - pocl  # [not win]

about:
  home: https://github.com/clesperanto/napari_pyclesperanto_assistant
  summary: GPU-accelerated image processing in napari using OpenCL
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
